import { CopyStatus, RecordStatus, Role } from '@library/shared';

// All visible UI text in one place (Hebrew)
export const HebrewTexts = {
  applicationName: 'מערכת ניהול ספרייה',

  navigation: {
    dashboard: 'לוח בקרה',
    books: 'ספרים',
    browseBooks: 'עיון בספרים',
    members: 'מנויים',
    loans: 'השאלות',
    users: 'משתמשים',
    auditLogs: 'יומן פעולות',
    settings: 'הגדרות',
    profile: 'פרופיל',
    home: 'ראשי',
  },

  authentication: {
    loginTitle: 'התחברות',
    loginSubtitle: 'ברוכים הבאים למערכת הספרייה',
    loginButton: 'התחברות',
    registerTitle: 'הרשמה',
    registerSubtitle: 'יצירת חשבון חדש',
    registerButton: 'הרשמה',
    logout: 'התנתקות',
    noAccountQuestion: 'אין לך חשבון?',
    registerLink: 'להרשמה',
    haveAccountQuestion: 'כבר יש לך חשבון?',
    loginLink: 'להתחברות',
    invalidCredentials: 'אימייל או סיסמה שגויים',
    emailAlreadyRegistered: 'כתובת האימייל כבר רשומה במערכת',
    registrationSucceeded: 'ההרשמה הושלמה בהצלחה, ניתן להתחבר',
    sessionExpired: 'פג תוקף ההתחברות, יש להתחבר מחדש',
    passwordsDoNotMatch: 'הסיסמאות אינן תואמות',
    personalDetailsSection: 'פרטים אישיים',
    addressSection: 'כתובת',
  },

  fields: {
    email: 'אימייל',
    password: 'סיסמה',
    confirmPassword: 'אימות סיסמה',
    firstName: 'שם פרטי',
    lastName: 'שם משפחה',
    phoneNumber: 'טלפון',
    street: 'רחוב',
    houseNumber: 'מספר בית',
    apartmentOrUnit: 'דירה',
    city: 'עיר',
    postalCode: 'מיקוד (לא חובה)',
    currentPassword: 'סיסמה נוכחית',
    newPassword: 'סיסמה חדשה',
    confirmNewPassword: 'אימות סיסמה חדשה',
  },

  errors: {
    unauthorizedTitle: 'אין הרשאה',
    unauthorizedDescription: 'אין לך הרשאה לצפות בעמוד זה.',
    notFoundTitle: 'העמוד לא נמצא',
    notFoundDescription: 'העמוד שחיפשת אינו קיים או שהועבר.',
    backToHome: 'חזרה לדף הראשי',
    invalidInput: 'הנתונים שהוזנו אינם תקינים',
    forbiddenAction: 'אין לך הרשאה לבצע פעולה זו',
    recordNotFound: 'הרשומה המבוקשת לא נמצאה',
    conflict: 'הפעולה מתנגשת בנתונים קיימים',
    serverError: 'אירעה שגיאה בשרת, נסו שוב מאוחר יותר',
    networkError: 'אין חיבור לשרת, בדקו את החיבור ונסו שוב',
  },

  profile: {
    pageTitle: 'הפרופיל שלי',
    personalDetailsTitle: 'פרטים אישיים',
    saveChanges: 'שמירת שינויים',
    profileUpdated: 'הפרטים עודכנו בהצלחה',
    changePasswordTitle: 'שינוי סיסמה',
    changePasswordButton: 'עדכון סיסמה',
    passwordChanged: 'הסיסמה עודכנה בהצלחה',
    incorrectCurrentPassword: 'הסיסמה הנוכחית שגויה',
    accountInformationTitle: 'פרטי חשבון',
    role: 'תפקיד',
    membershipStatus: 'סטטוס מנוי',
    lastLogin: 'התחברות אחרונה',
    noLastLogin: 'אין נתון',
  },

  membershipStatuses: {
    [RecordStatus.ACTIVE]: 'מנוי פעיל',
    [RecordStatus.DISABLED]: 'מנוי מושבת',
  },

  placeholders: {
    comingSoon: 'העמוד בפיתוח ויהיה זמין בקרוב.',
    dashboardWelcome: 'שלום',
  },

  catalog: {
    booksTab: 'ספרים',
    authorsTab: 'מחברים',
    categoriesTab: 'קטגוריות',
    publishersTab: 'הוצאות לאור',

    authorsTitle: 'מחברים',
    addAuthor: 'הוספת מחבר',
    createAuthorTitle: 'מחבר חדש',
    editAuthorTitle: 'עריכת מחבר',
    authorCreated: 'המחבר נוסף בהצלחה',
    authorUpdated: 'פרטי המחבר עודכנו',
    authorDisabled: 'המחבר הושבת',
    authorReactivated: 'המחבר הופעל מחדש',
    noAuthors: 'לא נמצאו מחברים',

    publishersTitle: 'הוצאות לאור',
    addPublisher: 'הוספת הוצאה לאור',
    createPublisherTitle: 'הוצאה לאור חדשה',
    editPublisherTitle: 'עריכת הוצאה לאור',
    publisherCreated: 'ההוצאה לאור נוספה בהצלחה',
    publisherUpdated: 'פרטי ההוצאה לאור עודכנו',
    publisherDisabled: 'ההוצאה לאור הושבתה',
    publisherReactivated: 'ההוצאה לאור הופעלה מחדש',
    duplicatePublisherName: 'כבר קיימת הוצאה לאור בשם זה',
    noPublishers: 'לא נמצאו הוצאות לאור',

    categoriesTitle: 'קטגוריות',
    addCategory: 'הוספת קטגוריה',
    createCategoryTitle: 'קטגוריה חדשה',
    editCategoryTitle: 'עריכת קטגוריה',
    categoryCreated: 'הקטגוריה נוספה בהצלחה',
    categoryUpdated: 'הקטגוריה עודכנה',
    categoryDisabled: 'הקטגוריה הושבתה',
    categoryReactivated: 'הקטגוריה הופעלה מחדש',
    duplicateCategoryName: 'כבר קיימת קטגוריה בשם זה',
    noCategories: 'לא נמצאו קטגוריות',

    firstNameColumn: 'שם פרטי',
    lastNameColumn: 'שם משפחה',
    biographyColumn: 'ביוגרפיה',
    nameColumn: 'שם',
    descriptionColumn: 'תיאור',
    publisherNameField: 'שם ההוצאה',
    categoryNameField: 'שם הקטגוריה',
  },

  books: {
    addBook: 'הוספת ספר',
    newBookTitle: 'ספר חדש',
    editBookTitle: 'עריכת ספר',
    bookDetailsBreadcrumb: 'פרטי ספר',
    editBreadcrumb: 'עריכה',
    noBooks: 'לא נמצאו ספרים',
    searchPlaceholder: 'חיפוש לפי שם, ISBN או מחבר',
    categoryFilter: 'קטגוריה',
    authorFilter: 'מחבר',
    publisherFilter: 'הוצאה לאור',
    languageFilter: 'שפה',
    availabilityFilter: 'זמינות',
    allOption: 'הכל',
    availableOption: 'זמינים להשאלה',
    unavailableOption: 'לא זמינים',
    sortLabel: 'מיון',
    sortByTitle: 'שם הספר (א-ת)',
    sortByNewest: 'שנת הוצאה (חדש לישן)',
    sortByRecentlyAdded: 'נוספו לאחרונה',
    clearFilters: 'ניקוי סינון',
    availableCopies: (available: number, total: number) => `זמין (${available}/${total})`,
    notAvailable: 'לא זמין כרגע',
    disabledBook: 'ספר מושבת',
    titleField: 'שם הספר',
    isbnField: 'ISBN',
    isbnHelp: '10 או 13 ספרות, מקפים מותרים',
    publisherField: 'הוצאה לאור',
    authorsField: 'מחברים',
    authorsHelp: 'המחבר הראשון ברשימה הוא המחבר הראשי',
    categoriesField: 'קטגוריות',
    publicationYearField: 'שנת הוצאה',
    languageField: 'שפה',
    imageUrlField: 'קישור לתמונת כריכה',
    descriptionField: 'תיאור',
    bookCreated: 'הספר נוסף בהצלחה',
    bookUpdated: 'הספר עודכן בהצלחה',
    bookDisabled: 'הספר הושבת',
    bookReactivated: 'הספר הופעל מחדש',
    duplicateIsbn: 'כבר קיים ספר עם ISBN זה',
    invalidReferences: 'המחבר, הקטגוריה או ההוצאה שנבחרו אינם פעילים',
    publisherRequired: 'יש לבחור הוצאה לאור',
    authorsRequired: 'יש לבחור לפחות מחבר אחד',
    isbnLabel: 'ISBN',
    publicationYearLabel: 'שנת הוצאה',
    languageLabel: 'שפה',
    publisherLabel: 'הוצאה לאור',
    categoriesLabel: 'קטגוריות',
    primaryAuthor: 'מחבר ראשי',
    noDescription: 'אין תיאור לספר זה',
    copiesTitle: 'עותקים',
    noCopies: 'אין עותקים לספר זה',
    barcodeColumn: 'ברקוד',
    copyStatusColumn: 'סטטוס',
    acquisitionDateColumn: 'תאריך רכישה',
    changeStatusColumn: 'שינוי סטטוס',
    newCopyBarcode: 'ברקוד לעותק חדש',
    addCopy: 'הוספת עותק',
    copyAdded: 'העותק נוסף',
    copyStatusChanged: 'סטטוס העותק עודכן',
    duplicateBarcode: 'כבר קיים עותק עם ברקוד זה',
    copyOnLoanHint: 'העותק מושאל — שינוי סטטוס אפשרי לאחר החזרה',
    bookNotFound: 'הספר לא נמצא',
  },

  copyStatuses: {
    [CopyStatus.AVAILABLE]: 'זמין',
    [CopyStatus.ON_LOAN]: 'מושאל',
    [CopyStatus.DISABLED]: 'מושבת',
    [CopyStatus.LOST]: 'אבד',
    [CopyStatus.DAMAGED]: 'פגום',
  },

  common: {
    search: 'חיפוש',
    statusFilter: 'סטטוס',
    allStatuses: 'הכל',
    statusColumn: 'סטטוס',
    actionsColumn: 'פעולות',
    edit: 'עריכה',
    disable: 'השבתה',
    reactivate: 'הפעלה מחדש',
    save: 'שמירה',
    cancel: 'ביטול',
    confirm: 'אישור',
    retry: 'נסו שוב',
    rowsPerPage: 'שורות בעמוד',
    disableConfirmationTitle: 'אישור השבתה',
    disableConfirmationText: 'להשבית את "{name}"? הרשומה תישמר בהיסטוריה וניתן להפעיל אותה מחדש.',
    displayedRows: (from: number, to: number, count: number) => `${from}–${to} מתוך ${count}`,
  },

  recordStatuses: {
    [RecordStatus.ACTIVE]: 'פעיל',
    [RecordStatus.DISABLED]: 'מושבת',
  },

  roles: {
    [Role.ADMIN]: 'מנהל מערכת',
    [Role.LIBRARIAN]: 'ספרן',
    [Role.MEMBER]: 'מנוי',
    [Role.VIEWER]: 'אורח',
  },
} as const;
