import { RecordStatus, Role } from '@library/shared';

// All visible UI text in one place (Hebrew)
export const HebrewTexts = {
  applicationName: 'מערכת ניהול ספרייה',

  navigation: {
    dashboard: 'לוח בקרה',
    books: 'ספרים',
    browseBooks: 'עיון בספרים',
    members: 'מנויים',
    loans: 'השאלות',
    users: 'משתמשים',
    auditLogs: 'יומן פעולות',
    settings: 'הגדרות',
    profile: 'פרופיל',
    home: 'ראשי',
  },

  authentication: {
    loginTitle: 'התחברות',
    loginSubtitle: 'ברוכים הבאים למערכת הספרייה',
    loginButton: 'התחברות',
    registerTitle: 'הרשמה',
    registerSubtitle: 'יצירת חשבון חדש',
    registerButton: 'הרשמה',
    logout: 'התנתקות',
    noAccountQuestion: 'אין לך חשבון?',
    registerLink: 'להרשמה',
    haveAccountQuestion: 'כבר יש לך חשבון?',
    loginLink: 'להתחברות',
    invalidCredentials: 'אימייל או סיסמה שגויים',
    emailAlreadyRegistered: 'כתובת האימייל כבר רשומה במערכת',
    registrationSucceeded: 'ההרשמה הושלמה בהצלחה, ניתן להתחבר',
    sessionExpired: 'פג תוקף ההתחברות, יש להתחבר מחדש',
    passwordsDoNotMatch: 'הסיסמאות אינן תואמות',
    personalDetailsSection: 'פרטים אישיים',
    addressSection: 'כתובת',
  },

  fields: {
    email: 'אימייל',
    password: 'סיסמה',
    confirmPassword: 'אימות סיסמה',
    firstName: 'שם פרטי',
    lastName: 'שם משפחה',
    phoneNumber: 'טלפון',
    street: 'רחוב',
    houseNumber: 'מספר בית',
    apartmentOrUnit: 'דירה',
    city: 'עיר',
    postalCode: 'מיקוד (לא חובה)',
    currentPassword: 'סיסמה נוכחית',
    newPassword: 'סיסמה חדשה',
    confirmNewPassword: 'אימות סיסמה חדשה',
  },

  errors: {
    unauthorizedTitle: 'אין הרשאה',
    unauthorizedDescription: 'אין לך הרשאה לצפות בעמוד זה.',
    notFoundTitle: 'העמוד לא נמצא',
    notFoundDescription: 'העמוד שחיפשת אינו קיים או שהועבר.',
    backToHome: 'חזרה לדף הראשי',
    invalidInput: 'הנתונים שהוזנו אינם תקינים',
    forbiddenAction: 'אין לך הרשאה לבצע פעולה זו',
    recordNotFound: 'הרשומה המבוקשת לא נמצאה',
    conflict: 'הפעולה מתנגשת בנתונים קיימים',
    serverError: 'אירעה שגיאה בשרת, נסו שוב מאוחר יותר',
    networkError: 'אין חיבור לשרת, בדקו את החיבור ונסו שוב',
  },

  profile: {
    pageTitle: 'הפרופיל שלי',
    personalDetailsTitle: 'פרטים אישיים',
    saveChanges: 'שמירת שינויים',
    profileUpdated: 'הפרטים עודכנו בהצלחה',
    changePasswordTitle: 'שינוי סיסמה',
    changePasswordButton: 'עדכון סיסמה',
    passwordChanged: 'הסיסמה עודכנה בהצלחה',
    incorrectCurrentPassword: 'הסיסמה הנוכחית שגויה',
    accountInformationTitle: 'פרטי חשבון',
    role: 'תפקיד',
    membershipStatus: 'סטטוס מנוי',
    lastLogin: 'התחברות אחרונה',
    noLastLogin: 'אין נתון',
  },

  membershipStatuses: {
    [RecordStatus.ACTIVE]: 'מנוי פעיל',
    [RecordStatus.DISABLED]: 'מנוי מושבת',
  },

  placeholders: {
    comingSoon: 'העמוד בפיתוח ויהיה זמין בקרוב.',
    dashboardWelcome: 'שלום',
  },

  catalog: {
    booksTab: 'ספרים',
    authorsTab: 'מחברים',
    categoriesTab: 'קטגוריות',
    publishersTab: 'הוצאות לאור',

    authorsTitle: 'מחברים',
    addAuthor: 'הוספת מחבר',
    createAuthorTitle: 'מחבר חדש',
    editAuthorTitle: 'עריכת מחבר',
    authorCreated: 'המחבר נוסף בהצלחה',
    authorUpdated: 'פרטי המחבר עודכנו',
    authorDisabled: 'המחבר הושבת',
    authorReactivated: 'המחבר הופעל מחדש',
    noAuthors: 'לא נמצאו מחברים',

    publishersTitle: 'הוצאות לאור',
    addPublisher: 'הוספת הוצאה לאור',
    createPublisherTitle: 'הוצאה לאור חדשה',
    editPublisherTitle: 'עריכת הוצאה לאור',
    publisherCreated: 'ההוצאה לאור נוספה בהצלחה',
    publisherUpdated: 'פרטי ההוצאה לאור עודכנו',
    publisherDisabled: 'ההוצאה לאור הושבתה',
    publisherReactivated: 'ההוצאה לאור הופעלה מחדש',
    duplicatePublisherName: 'כבר קיימת הוצאה לאור בשם זה',
    noPublishers: 'לא נמצאו הוצאות לאור',

    categoriesTitle: 'קטגוריות',
    addCategory: 'הוספת קטגוריה',
    createCategoryTitle: 'קטגוריה חדשה',
    editCategoryTitle: 'עריכת קטגוריה',
    categoryCreated: 'הקטגוריה נוספה בהצלחה',
    categoryUpdated: 'הקטגוריה עודכנה',
    categoryDisabled: 'הקטגוריה הושבתה',
    categoryReactivated: 'הקטגוריה הופעלה מחדש',
    duplicateCategoryName: 'כבר קיימת קטגוריה בשם זה',
    noCategories: 'לא נמצאו קטגוריות',

    firstNameColumn: 'שם פרטי',
    lastNameColumn: 'שם משפחה',
    biographyColumn: 'ביוגרפיה',
    nameColumn: 'שם',
    descriptionColumn: 'תיאור',
    publisherNameField: 'שם ההוצאה',
    categoryNameField: 'שם הקטגוריה',
  },

  common: {
    search: 'חיפוש',
    statusFilter: 'סטטוס',
    allStatuses: 'הכל',
    statusColumn: 'סטטוס',
    actionsColumn: 'פעולות',
    edit: 'עריכה',
    disable: 'השבתה',
    reactivate: 'הפעלה מחדש',
    save: 'שמירה',
    cancel: 'ביטול',
    confirm: 'אישור',
    rowsPerPage: 'שורות בעמוד',
    disableConfirmationTitle: 'אישור השבתה',
    disableConfirmationText: 'להשבית את "{name}"? הרשומה תישמר בהיסטוריה וניתן להפעיל אותה מחדש.',
    displayedRows: (from: number, to: number, count: number) => `${from}–${to} מתוך ${count}`,
  },

  recordStatuses: {
    [RecordStatus.ACTIVE]: 'פעיל',
    [RecordStatus.DISABLED]: 'מושבת',
  },

  roles: {
    [Role.ADMIN]: 'מנהל מערכת',
    [Role.LIBRARIAN]: 'ספרן',
    [Role.MEMBER]: 'מנוי',
    [Role.VIEWER]: 'אורח',
  },
} as const;
