import {
  BusinessErrorCode,
  CopyStatus,
  LoanStatus,
  RecordStatus,
  Role,
  SystemSettingKey,
} from '@library/shared';

// All visible UI text in one place (Hebrew)
export const HebrewTexts = {
  applicationName: 'מערכת ניהול ספרייה',

  navigation: {
    dashboard: 'לוח בקרה',
    books: 'ספרים',
    browseBooks: 'עיון בספרים',
    members: 'מנויים',
    loans: 'השאלות',
    users: 'משתמשים',
    auditLogs: 'יומן פעולות',
    settings: 'הגדרות',
    profile: 'פרופיל',
    home: 'ראשי',
  },

  authentication: {
    loginTitle: 'התחברות',
    loginSubtitle: 'ברוכים הבאים למערכת הספרייה',
    loginButton: 'התחברות',
    registerTitle: 'הרשמה',
    registerSubtitle: 'יצירת חשבון חדש',
    registerButton: 'הרשמה',
    logout: 'התנתקות',
    noAccountQuestion: 'אין לך חשבון?',
    registerLink: 'להרשמה',
    haveAccountQuestion: 'כבר יש לך חשבון?',
    loginLink: 'להתחברות',
    invalidCredentials: 'אימייל או סיסמה שגויים',
    emailAlreadyRegistered: 'כתובת האימייל כבר רשומה במערכת',
    registrationSucceeded: 'ההרשמה הושלמה בהצלחה, ניתן להתחבר',
    sessionExpired: 'פג תוקף ההתחברות, יש להתחבר מחדש',
    passwordsDoNotMatch: 'הסיסמאות אינן תואמות',
    personalDetailsSection: 'פרטים אישיים',
    addressSection: 'כתובת',
  },

  fields: {
    email: 'אימייל',
    password: 'סיסמה',
    confirmPassword: 'אימות סיסמה',
    firstName: 'שם פרטי',
    lastName: 'שם משפחה',
    phoneNumber: 'טלפון',
    street: 'רחוב',
    houseNumber: 'מספר בית',
    apartmentOrUnit: 'דירה',
    city: 'עיר',
    postalCode: 'מיקוד (לא חובה)',
    currentPassword: 'סיסמה נוכחית',
    newPassword: 'סיסמה חדשה',
    confirmNewPassword: 'אימות סיסמה חדשה',
  },

  errors: {
    unauthorizedTitle: 'אין הרשאה',
    unauthorizedDescription: 'אין לך הרשאה לצפות בעמוד זה.',
    notFoundTitle: 'העמוד לא נמצא',
    notFoundDescription: 'העמוד שחיפשת אינו קיים או שהועבר.',
    backToHome: 'חזרה לדף הראשי',
    invalidInput: 'הנתונים שהוזנו אינם תקינים',
    forbiddenAction: 'אין לך הרשאה לבצע פעולה זו',
    recordNotFound: 'הרשומה המבוקשת לא נמצאה',
    conflict: 'הפעולה מתנגשת בנתונים קיימים',
    serverError: 'אירעה שגיאה בשרת, נסו שוב מאוחר יותר',
    networkError: 'אין חיבור לשרת, בדקו את החיבור ונסו שוב',
  },

  profile: {
    pageTitle: 'הפרופיל שלי',
    personalDetailsTitle: 'פרטים אישיים',
    saveChanges: 'שמירת שינויים',
    profileUpdated: 'הפרטים עודכנו בהצלחה',
    changePasswordTitle: 'שינוי סיסמה',
    changePasswordButton: 'עדכון סיסמה',
    passwordChanged: 'הסיסמה עודכנה בהצלחה',
    incorrectCurrentPassword: 'הסיסמה הנוכחית שגויה',
    accountInformationTitle: 'פרטי חשבון',
    role: 'תפקיד',
    membershipStatus: 'סטטוס מנוי',
    lastLogin: 'התחברות אחרונה',
    noLastLogin: 'אין נתון',
  },

  membershipStatuses: {
    [RecordStatus.ACTIVE]: 'מנוי פעיל',
    [RecordStatus.DISABLED]: 'מנוי מושבת',
  },

  placeholders: {
    comingSoon: 'העמוד בפיתוח ויהיה זמין בקרוב.',
    dashboardWelcome: 'שלום',
  },

  catalog: {
    booksTab: 'ספרים',
    authorsTab: 'מחברים',
    categoriesTab: 'קטגוריות',
    publishersTab: 'הוצאות לאור',

    authorsTitle: 'מחברים',
    addAuthor: 'הוספת מחבר',
    createAuthorTitle: 'מחבר חדש',
    editAuthorTitle: 'עריכת מחבר',
    authorCreated: 'המחבר נוסף בהצלחה',
    authorUpdated: 'פרטי המחבר עודכנו',
    authorDisabled: 'המחבר הושבת',
    authorReactivated: 'המחבר הופעל מחדש',
    noAuthors: 'לא נמצאו מחברים',

    publishersTitle: 'הוצאות לאור',
    addPublisher: 'הוספת הוצאה לאור',
    createPublisherTitle: 'הוצאה לאור חדשה',
    editPublisherTitle: 'עריכת הוצאה לאור',
    publisherCreated: 'ההוצאה לאור נוספה בהצלחה',
    publisherUpdated: 'פרטי ההוצאה לאור עודכנו',
    publisherDisabled: 'ההוצאה לאור הושבתה',
    publisherReactivated: 'ההוצאה לאור הופעלה מחדש',
    duplicatePublisherName: 'כבר קיימת הוצאה לאור בשם זה',
    noPublishers: 'לא נמצאו הוצאות לאור',

    categoriesTitle: 'קטגוריות',
    addCategory: 'הוספת קטגוריה',
    createCategoryTitle: 'קטגוריה חדשה',
    editCategoryTitle: 'עריכת קטגוריה',
    categoryCreated: 'הקטגוריה נוספה בהצלחה',
    categoryUpdated: 'הקטגוריה עודכנה',
    categoryDisabled: 'הקטגוריה הושבתה',
    categoryReactivated: 'הקטגוריה הופעלה מחדש',
    duplicateCategoryName: 'כבר קיימת קטגוריה בשם זה',
    noCategories: 'לא נמצאו קטגוריות',

    firstNameColumn: 'שם פרטי',
    lastNameColumn: 'שם משפחה',
    biographyColumn: 'ביוגרפיה',
    nameColumn: 'שם',
    descriptionColumn: 'תיאור',
    publisherNameField: 'שם ההוצאה',
    categoryNameField: 'שם הקטגוריה',
  },

  books: {
    addBook: 'הוספת ספר',
    newBookTitle: 'ספר חדש',
    editBookTitle: 'עריכת ספר',
    bookDetailsBreadcrumb: 'פרטי ספר',
    editBreadcrumb: 'עריכה',
    noBooks: 'לא נמצאו ספרים',
    searchPlaceholder: 'חיפוש לפי שם, ISBN או מחבר',
    categoryFilter: 'קטגוריה',
    authorFilter: 'מחבר',
    publisherFilter: 'הוצאה לאור',
    languageFilter: 'שפה',
    availabilityFilter: 'זמינות',
    allOption: 'הכל',
    availableOption: 'זמינים להשאלה',
    unavailableOption: 'לא זמינים',
    sortLabel: 'מיון',
    sortByTitle: 'שם הספר (א-ת)',
    sortByNewest: 'שנת הוצאה (חדש לישן)',
    sortByRecentlyAdded: 'נוספו לאחרונה',
    clearFilters: 'ניקוי סינון',
    availableCopies: (available: number, total: number) => `זמין (${available}/${total})`,
    notAvailable: 'לא זמין כרגע',
    disabledBook: 'ספר מושבת',
    titleField: 'שם הספר',
    isbnField: 'ISBN',
    isbnHelp: '10 או 13 ספרות, מקפים מותרים',
    publisherField: 'הוצאה לאור',
    authorsField: 'מחברים',
    authorsHelp: 'המחבר הראשון ברשימה הוא המחבר הראשי',
    categoriesField: 'קטגוריות',
    publicationYearField: 'שנת הוצאה',
    languageField: 'שפה',
    imageUrlField: 'קישור לתמונת כריכה',
    descriptionField: 'תיאור',
    bookCreated: 'הספר נוסף בהצלחה',
    bookUpdated: 'הספר עודכן בהצלחה',
    bookDisabled: 'הספר הושבת',
    bookReactivated: 'הספר הופעל מחדש',
    duplicateIsbn: 'כבר קיים ספר עם ISBN זה',
    invalidReferences: 'המחבר, הקטגוריה או ההוצאה שנבחרו אינם פעילים',
    publisherRequired: 'יש לבחור הוצאה לאור',
    authorsRequired: 'יש לבחור לפחות מחבר אחד',
    isbnLabel: 'ISBN',
    publicationYearLabel: 'שנת הוצאה',
    languageLabel: 'שפה',
    publisherLabel: 'הוצאה לאור',
    categoriesLabel: 'קטגוריות',
    primaryAuthor: 'מחבר ראשי',
    noDescription: 'אין תיאור לספר זה',
    copiesTitle: 'עותקים',
    noCopies: 'אין עותקים לספר זה',
    barcodeColumn: 'ברקוד',
    copyStatusColumn: 'סטטוס',
    acquisitionDateColumn: 'תאריך רכישה',
    changeStatusColumn: 'שינוי סטטוס',
    newCopyBarcode: 'ברקוד לעותק חדש',
    addCopy: 'הוספת עותק',
    copyAdded: 'העותק נוסף',
    copyStatusChanged: 'סטטוס העותק עודכן',
    duplicateBarcode: 'כבר קיים עותק עם ברקוד זה',
    copyOnLoanHint: 'העותק מושאל — שינוי סטטוס אפשרי לאחר החזרה',
    bookNotFound: 'הספר לא נמצא',
  },

  members: {
    pageTitle: 'מנויים',
    addMember: 'הוספת מנוי',
    newMemberTitle: 'מנוי חדש',
    editMemberTitle: 'עריכת מנוי',
    memberDetailsBreadcrumb: 'פרטי מנוי',
    editBreadcrumb: 'עריכה',
    searchPlaceholder: 'חיפוש לפי שם מלא, אימייל או טלפון',
    noMembers: 'לא נמצאו מנויים',
    nameColumn: 'שם',
    emailColumn: 'אימייל',
    phoneColumn: 'טלפון',
    cityColumn: 'עיר',
    registrationDateColumn: 'תאריך הצטרפות',
    statusColumn: 'סטטוס מנוי',
    detailsTab: 'פרטים',
    loansTab: 'השאלות',
    personalDetailsTitle: 'פרטים אישיים',
    addressTitle: 'כתובת',
    membershipTitle: 'מנוי',
    registrationDateLabel: 'תאריך הצטרפות',
    accountStatusLabel: 'חשבון התחברות',
    memberStatusLabel: 'סטטוס מנוי',
    disabledDateLabel: 'תאריך השבתה',
    createModeLabel: 'אופן ההוספה',
    linkExistingUserMode: 'קישור משתמש קיים',
    newPersonMode: 'אדם חדש',
    existingUserField: 'משתמש קיים (אורח)',
    existingUserHelp: 'חיפוש לפי שם או אימייל. מוצגים רק חשבונות אורח פעילים שאינם מנויים.',
    existingUserRequired: 'יש לבחור משתמש',
    initialPasswordField: 'סיסמה ראשונית',
    initialPasswordHelp: 'המנוי יוכל להחליף אותה בעמוד הפרופיל',
    memberCreated: 'המנוי נוסף בהצלחה',
    memberUpdated: 'פרטי המנוי עודכנו',
    memberDisabled: 'המנוי הושבת',
    memberReactivated: 'המנוי הופעל מחדש',
    alreadyMember: 'המשתמש שנבחר כבר רשום כמנוי',
    notEligible: 'רק חשבון אורח פעיל יכול להפוך למנוי',
    memberNotFound: 'המנוי לא נמצא',
    disabledMemberNote: 'המנוי מושבת: החשבון הפך לחשבון אורח ואינו יכול לקבל השאלות חדשות',
  },

  users: {
    pageTitle: 'משתמשים',
    addUser: 'הוספת משתמש',
    newUserTitle: 'משתמש חדש',
    editUserTitle: 'עריכת משתמש',
    userDetailsBreadcrumb: 'פרטי משתמש',
    editBreadcrumb: 'עריכה',
    searchPlaceholder: 'חיפוש לפי שם מלא או אימייל',
    noUsers: 'לא נמצאו משתמשים',
    nameColumn: 'שם',
    emailColumn: 'אימייל',
    roleColumn: 'תפקיד',
    accountStatusColumn: 'סטטוס חשבון',
    lastLoginColumn: 'התחברות אחרונה',
    roleFilter: 'תפקיד',
    allRoles: 'כל התפקידים',
    roleField: 'תפקיד',
    initialPasswordField: 'סיסמה ראשונית',
    initialPasswordHelp: 'המשתמש יוכל להחליף אותה בעמוד הפרופיל',
    memberRoleHint: 'משתמש בתפקיד מנוי יקבל גם כרטיס מנוי',
    accountTitle: 'חשבון',
    personalDetailsTitle: 'פרטים אישיים',
    addressTitle: 'כתובת',
    createdDateLabel: 'נוצר בתאריך',
    disabledDateLabel: 'הושבת בתאריך',
    membershipLabel: 'כרטיס מנוי',
    noMembership: 'אין',
    openMembership: 'לכרטיס המנוי',
    changeRole: 'שינוי תפקיד',
    changeRoleTitle: 'שינוי תפקיד',
    changeRoleHint:
      'מעבר לתפקיד מנוי יוצר או מפעיל מחדש כרטיס מנוי; מעבר לתפקיד אחר משבית כרטיס מנוי פעיל.',
    ownAccountNote: 'זהו החשבון שלך: לא ניתן לשנות את התפקיד או הסטטוס שלו.',
    userCreated: 'המשתמש נוסף בהצלחה',
    userUpdated: 'פרטי המשתמש עודכנו',
    roleChanged: 'התפקיד עודכן',
    userDisabled: 'החשבון הושבת',
    userReactivated: 'החשבון הופעל מחדש',
    lastActiveAdmin: 'לא ניתן להסיר את מנהל המערכת הפעיל האחרון',
    sameRole: 'למשתמש כבר יש תפקיד זה',
    userNotFound: 'המשתמש לא נמצא',
    disabledAccountNote: 'החשבון מושבת: המשתמש אינו יכול להתחבר למערכת',
  },

  settings: {
    pageTitle: 'הגדרות מערכת',
    pageDescription: 'ערכים שחלים על כל הספרייה. כל שינוי נרשם ביומן הפעולות.',
    valueField: 'ערך',
    defaultValue: (value: number) => `ברירת מחדל: ${value}`,
    lastUpdated: (date: string) => `עודכן לאחרונה: ${date}`,
    usingDefault: 'בשימוש ערך ברירת המחדל',
    settingSaved: 'ההגדרה נשמרה',
    definitions: {
      [SystemSettingKey.LOAN_PERIOD_DAYS]: {
        title: 'תקופת השאלה',
        description: 'מספר הימים עד מועד ההחזרה של השאלה חדשה (1–90).',
        unit: 'ימים',
      },
      [SystemSettingKey.MAX_ACTIVE_LOANS_PER_MEMBER]: {
        title: 'מספר השאלות מרבי למנוי',
        description: 'כמה ספרים מנוי יכול להחזיק בהשאלה בו-זמנית (1–20).',
        unit: 'ספרים',
      },
    },
  },

  addressFields: {
    street: 'רחוב',
    houseNumber: 'מספר בית',
    apartmentOrUnit: 'דירה',
    city: 'עיר',
    postalCode: 'מיקוד (לא חובה)',
  },

  loans: {
    pageTitle: 'השאלות',
    ownLoansTitle: 'ההשאלות שלי',
    newLoan: 'השאלה חדשה',
    allTab: 'כל ההשאלות',
    pendingReturnsTab: 'בקשות החזרה',
    overdueTab: 'באיחור',
    searchPlaceholder: 'חיפוש לפי שם ספר, ברקוד או מנוי',
    memberFilter: 'מנוי',
    bookFilter: 'ספר',
    bookColumn: 'ספר',
    memberColumn: 'מנוי',
    barcodeColumn: 'ברקוד',
    loanDateColumn: 'תאריך השאלה',
    dueDateColumn: 'להחזיר עד',
    statusColumn: 'סטטוס',
    actionsColumn: 'פעולות',
    noLoans: 'לא נמצאו השאלות',
    pastDue: 'באיחור',
    loanDetailsBreadcrumb: 'פרטי השאלה',
    loanNotFound: 'ההשאלה לא נמצאה',
    detailsCardTitle: 'פרטי ההשאלה',
    timelineCardTitle: 'מהלך ההשאלה',
    createdBy: 'הושאל על ידי',
    returnProcessedBy: 'ההחזרה נקלטה על ידי',
    copyStatus: 'מצב העותק',

    requestReturn: 'בקשת החזרה',
    cancelReturnRequest: 'ביטול בקשת החזרה',
    processReturn: 'קליטת החזרה',
    cancelLoan: 'ביטול השאלה',
    returnRequested: 'בקשת ההחזרה נשלחה לספרייה',
    returnRequestCancelled: 'בקשת ההחזרה בוטלה',
    returnProcessed: 'ההחזרה נקלטה',
    loanCancelled: 'ההשאלה בוטלה',
    loanCreated: 'ההשאלה נוצרה בהצלחה',
    cancelLoanConfirmationText:
      'לבטל את השאלת "{title}"? העותק יחזור למדף. פעולה זו מיועדת להשאלה שנרשמה בטעות.',

    processReturnText: 'באיזה מצב הוחזר העותק {barcode}?',
    copyConditionField: 'מצב העותק',
    copyConditions: {
      [CopyStatus.AVAILABLE]: 'תקין - חוזר למדף',
      [CopyStatus.DAMAGED]: 'פגום',
      [CopyStatus.LOST]: 'אבד',
    },

    memberField: 'מנוי',
    bookField: 'ספר',
    barcodeField: 'ברקוד עותק (לא חובה)',
    barcodeHelp: 'השאירו ריק כדי להשאיל את העותק הזמין הראשון של הספר',
    memberRequired: 'יש לבחור מנוי',
    bookOrBarcodeRequired: 'יש לבחור ספר או להזין ברקוד',
    availableCopiesLabel: (count: number) => `${count} זמינים`,
    lend: 'השאלה',

    timelineCreated: 'הספר הושאל',
    timelineDueDate: 'מועד ההחזרה',
    timelineReturnRequested: 'נשלחה בקשת החזרה',
    timelineReturnRequestCancelled: 'בקשת ההחזרה בוטלה',
    timelineReturned: 'הספר הוחזר',
    timelineCancelled: 'ההשאלה בוטלה',
  },

  loanStatuses: {
    [LoanStatus.ACTIVE]: 'פעילה',
    [LoanStatus.RETURN_REQUESTED]: 'ממתינה להחזרה',
    [LoanStatus.RETURNED]: 'הוחזרה',
    [LoanStatus.OVERDUE]: 'באיחור',
    [LoanStatus.CANCELLED]: 'בוטלה',
  },

  // Messages for the loan business rules (error.code from the API)
  loanErrors: {
    [BusinessErrorCode.MEMBER_NOT_ACTIVE]: 'המנוי אינו פעיל ולא ניתן להשאיל לו ספרים',
    [BusinessErrorCode.BOOK_NOT_ACTIVE]: 'הספר מושבת ולא ניתן להשאיל אותו',
    [BusinessErrorCode.COPY_NOT_FOUND]: 'לא נמצא עותק עם הברקוד הזה',
    [BusinessErrorCode.COPY_NOT_AVAILABLE]: 'העותק אינו זמין להשאלה',
    [BusinessErrorCode.COPY_OF_OTHER_BOOK]: 'הברקוד שייך לעותק של ספר אחר',
    [BusinessErrorCode.NO_AVAILABLE_COPY]: 'אין כרגע עותק זמין של הספר',
    [BusinessErrorCode.LOAN_LIMIT_REACHED]: 'המנוי הגיע למספר ההשאלות הפתוחות המרבי',
    [BusinessErrorCode.LOAN_STATUS_NOT_ALLOWED]: 'לא ניתן לבצע פעולה זו במצב הנוכחי של ההשאלה',
  },

  copyStatuses: {
    [CopyStatus.AVAILABLE]: 'זמין',
    [CopyStatus.ON_LOAN]: 'מושאל',
    [CopyStatus.DISABLED]: 'מושבת',
    [CopyStatus.LOST]: 'אבד',
    [CopyStatus.DAMAGED]: 'פגום',
  },

  common: {
    search: 'חיפוש',
    statusFilter: 'סטטוס',
    allStatuses: 'הכל',
    statusColumn: 'סטטוס',
    actionsColumn: 'פעולות',
    edit: 'עריכה',
    disable: 'השבתה',
    reactivate: 'הפעלה מחדש',
    save: 'שמירה',
    cancel: 'ביטול',
    confirm: 'אישור',
    retry: 'נסו שוב',
    rowsPerPage: 'שורות בעמוד',
    disableConfirmationTitle: 'אישור השבתה',
    disableConfirmationText: 'להשבית את "{name}"? הרשומה תישמר בהיסטוריה וניתן להפעיל אותה מחדש.',
    displayedRows: (from: number, to: number, count: number) => `${from}–${to} מתוך ${count}`,
  },

  recordStatuses: {
    [RecordStatus.ACTIVE]: 'פעיל',
    [RecordStatus.DISABLED]: 'מושבת',
  },

  roles: {
    [Role.ADMIN]: 'מנהל מערכת',
    [Role.LIBRARIAN]: 'ספרן',
    [Role.MEMBER]: 'מנוי',
    [Role.VIEWER]: 'אורח',
  },
} as const;
