// Every URL in the app, so links never use hard-coded strings
export const RoutePaths = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  UNAUTHORIZED: '/unauthorized',

  DASHBOARD: '/dashboard',
  BOOKS: '/books',
  NEW_BOOK: '/books/new',
  BOOK_DETAILS: '/books/:bookId',
  EDIT_BOOK: '/books/:bookId/edit',
  AUTHORS: '/books/authors',
  CATEGORIES: '/books/categories',
  PUBLISHERS: '/books/publishers',
  MEMBERS: '/members',
  NEW_MEMBER: '/members/new',
  MEMBER_DETAILS: '/members/:memberId',
  EDIT_MEMBER: '/members/:memberId/edit',
  LOANS: '/loans',
  LOAN_DETAILS: '/loans/:loanId',
  USERS: '/users',
  NEW_USER: '/users/new',
  USER_DETAILS: '/users/:userId',
  EDIT_USER: '/users/:userId/edit',
  AUDIT_LOGS: '/audit-logs',
  SETTINGS: '/settings',
  PROFILE: '/profile',
} as const;
