// Every action that can be written to the audit log - must match Prisma `ActionType`
export const ActionType = {
    // Users and authentication
    USER_CREATED: "USER_CREATED",
    USER_UPDATED: "USER_UPDATED",
    USER_DISABLED: "USER_DISABLED",
    USER_REACTIVATED: "USER_REACTIVATED",
    USER_ROLE_CHANGED: "USER_ROLE_CHANGED",
    USER_PASSWORD_CHANGED: "USER_PASSWORD_CHANGED",
    USER_LOGIN_SUCCEEDED: "USER_LOGIN_SUCCEEDED",
    USER_LOGIN_FAILED: "USER_LOGIN_FAILED",
    USER_LOGOUT: "USER_LOGOUT",

    // Members and addresses
    MEMBER_CREATED: "MEMBER_CREATED",
    MEMBER_UPDATED: "MEMBER_UPDATED",
    MEMBER_DISABLED: "MEMBER_DISABLED",
    MEMBER_REACTIVATED: "MEMBER_REACTIVATED",
    ADDRESS_UPDATED: "ADDRESS_UPDATED",

    // Catalog reference data
    AUTHOR_CREATED: "AUTHOR_CREATED",
    AUTHOR_UPDATED: "AUTHOR_UPDATED",
    AUTHOR_DISABLED: "AUTHOR_DISABLED",
    AUTHOR_REACTIVATED: "AUTHOR_REACTIVATED",
    PUBLISHER_CREATED: "PUBLISHER_CREATED",
    PUBLISHER_UPDATED: "PUBLISHER_UPDATED",
    PUBLISHER_DISABLED: "PUBLISHER_DISABLED",
    PUBLISHER_REACTIVATED: "PUBLISHER_REACTIVATED",
    CATEGORY_CREATED: "CATEGORY_CREATED",
    CATEGORY_UPDATED: "CATEGORY_UPDATED",
    CATEGORY_DISABLED: "CATEGORY_DISABLED",
    CATEGORY_REACTIVATED: "CATEGORY_REACTIVATED",

    // Books and copies
    BOOK_CREATED: "BOOK_CREATED",
    BOOK_UPDATED: "BOOK_UPDATED",
    BOOK_DISABLED: "BOOK_DISABLED",
    BOOK_REACTIVATED: "BOOK_REACTIVATED",
    BOOK_COPY_CREATED: "BOOK_COPY_CREATED",
    BOOK_COPY_UPDATED: "BOOK_COPY_UPDATED",
    BOOK_COPY_DISABLED: "BOOK_COPY_DISABLED",
    BOOK_COPY_REACTIVATED: "BOOK_COPY_REACTIVATED",
    BOOK_COPY_MARKED_LOST: "BOOK_COPY_MARKED_LOST",
    BOOK_COPY_MARKED_DAMAGED: "BOOK_COPY_MARKED_DAMAGED",

    // Loans
    LOAN_CREATED: "LOAN_CREATED",
    LOAN_UPDATED: "LOAN_UPDATED",
    LOAN_RETURN_REQUESTED: "LOAN_RETURN_REQUESTED",
    LOAN_RETURN_REQUEST_CANCELLED: "LOAN_RETURN_REQUEST_CANCELLED",
    LOAN_RETURN_PROCESSED: "LOAN_RETURN_PROCESSED",
    LOAN_CANCELLED: "LOAN_CANCELLED",
    LOAN_MARKED_OVERDUE: "LOAN_MARKED_OVERDUE",

    // System settings
    SYSTEM_SETTING_CREATED: "SYSTEM_SETTING_CREATED",
    SYSTEM_SETTING_UPDATED: "SYSTEM_SETTING_UPDATED",
    SYSTEM_SETTING_DISABLED: "SYSTEM_SETTING_DISABLED",
    SYSTEM_SETTING_REACTIVATED: "SYSTEM_SETTING_REACTIVATED",
} as const;

export type ActionType = (typeof ActionType)[keyof typeof ActionType];
